"""update laptop tbl

Revision ID: 1ae7fc1d26e1
Revises: e67b02a435fd
Create Date: 2026-06-11 20:50:09.984946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel as sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ae7fc1d26e1'
down_revision: Union[str, Sequence[str], None] = 'e67b02a435fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laptop_brands', 'icons_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('laptops', sa.Column('processor_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('laptops', sa.Column('gpu_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('laptops', 'cpu_benchmark')
    op.drop_column('laptops', 'gpu_benchmark')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptops', sa.Column('gpu_benchmark', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('laptops', sa.Column('cpu_benchmark', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('laptops', 'gpu_model')
    op.drop_column('laptops', 'processor_model')
    op.alter_column('laptop_brands', 'icons_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
