"""add review_laptop_link

Revision ID: 2d645c884ece
Revises: 6301c2f3b369
Create Date: 2026-08-24 18:04:14.675267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d645c884ece'
down_revision: Union[str, Sequence[str], None] = '6301c2f3b369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create review_laptop_link and backfill it from matched_laptop_id.

    matched_laptop_id is NOT dropped here. It stays live through the cutover so
    nothing breaks between this migration and the code that moves off it —
    process_raw_review still reads it. Dropping it is a later revision.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_laptop_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_review_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('laptop_id', sa.Uuid(), nullable=True),
    sa.Column('match_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('tie_width', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['laptop_family.id'], ),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptops.id'], ),
    sa.ForeignKeyConstraint(['raw_review_id'], ['raw_youtube_reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_review_id', 'family_id', 'laptop_id', name='uq_review_family_laptop')
    )
    op.create_index(op.f('ix_review_laptop_link_family_id'), 'review_laptop_link', ['family_id'], unique=False)
    op.create_index(op.f('ix_review_laptop_link_match_source'), 'review_laptop_link', ['match_source'], unique=False)
    op.create_index(op.f('ix_review_laptop_link_raw_review_id'), 'review_laptop_link', ['raw_review_id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: every non-null matched_laptop_id becomes one link.
    #
    # The CASE is the part that matters and the part that is only correct if
    # done now. PATCH /reviews/raw/{id}/match writes match_confidence = 100.0
    # for a human decision, so a human match is indistinguishable from a
    # perfect fuzzy score in the old column — 10 of the 19 matched rows are
    # human. Backfilling those as `auto` with a confidence of 100.0 would
    # poison match_source on day one: every consumer that trusts the flag
    # would treat ten human judgements as the highest-scoring automatic
    # matches in the corpus, which is exactly backwards. They become
    # match_source='human' with match_confidence NULL, because a human did not
    # score anything.
    #
    # 100.0 is not otherwise reachable: token_set_ratio can return 100, but no
    # auto-matched row in this table has it (measured — the auto rows top out
    # at 93.0), so the test is unambiguous for this backfill even though it
    # would not be a safe rule to apply going forward. That is why the column
    # exists rather than the heuristic being kept.
    #
    # family_id comes from the laptop's own family. The IS NOT NULL guard is
    # currently a no-op (all 19 resolve) but the column is NOT NULL, so an
    # ungrouped laptop must be skipped rather than abort the migration; a
    # review whose laptop has no family is left for a human to link.
    #
    # tie_width is NULL for every backfilled row: it was never measured at
    # match time, and inventing one would be worse than admitting it.
    op.execute(
        """
        INSERT INTO review_laptop_link (
            id, raw_review_id, family_id, laptop_id,
            match_source, match_confidence, tie_width, created_at
        )
        SELECT
            gen_random_uuid(),
            r.id,
            l.family_id,
            r.matched_laptop_id,
            CASE WHEN r.match_confidence = 100.0 THEN 'human' ELSE 'auto' END,
            CASE WHEN r.match_confidence = 100.0 THEN NULL ELSE r.match_confidence END,
            NULL,
            now()
        FROM raw_youtube_reviews r
        JOIN laptops l ON l.id = r.matched_laptop_id
        WHERE r.matched_laptop_id IS NOT NULL
          AND l.family_id IS NOT NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_laptop_link_raw_review_id'), table_name='review_laptop_link')
    op.drop_index(op.f('ix_review_laptop_link_match_source'), table_name='review_laptop_link')
    op.drop_index(op.f('ix_review_laptop_link_family_id'), table_name='review_laptop_link')
    op.drop_table('review_laptop_link')
    # ### end Alembic commands ###
