"""replace raw_price_rm with raw_prices array

Revision ID: 3ebc95cb5885
Revises: ddbc0e4de136
Create Date: 2026-06-09 19:40:04.335134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ebc95cb5885'
down_revision: Union[str, Sequence[str], None] = 'ddbc0e4de136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_scrap_laptops', sa.Column('raw_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('raw_scrap_laptops', 'raw_price_rm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_scrap_laptops', sa.Column('raw_price_rm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('raw_scrap_laptops', 'raw_prices')
    # ### end Alembic commands ###
