"""init_all_tables

Revision ID: 453fffc97e7b
Revises: 
Create Date: 2026-06-29 17:22:30.813312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '453fffc97e7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpu_benchmarks',
    sa.Column('cpu_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpu_mark', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpu_benchmarks_cpu_name'), 'cpu_benchmarks', ['cpu_name'], unique=True)
    op.create_table('gpu_benchmarks',
    sa.Column('gpu_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gpu_mark', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpu_benchmarks_gpu_name'), 'gpu_benchmarks', ['gpu_name'], unique=True)
    op.create_table('laptop_brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_scrape_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icons_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laptop_brands_name'), 'laptop_brands', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('occupation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('laptop_scrape_urls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['laptop_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laptop_scrape_urls_url'), 'laptop_scrape_urls', ['url'], unique=True)
    op.create_table('laptop_user_preference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.JSON(), nullable=True),
    sa.Column('priorities', sa.JSON(), nullable=True),
    sa.Column('screen_size', sa.JSON(), nullable=True),
    sa.Column('portability', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand_preferences', sa.JSON(), nullable=True),
    sa.Column('tech_savviness', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laptop_user_preference_user_id'), 'laptop_user_preference', ['user_id'], unique=False)
    op.create_table('laptops',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('model_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('price_rm', sa.Float(), nullable=False),
    sa.Column('processor_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processor_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processor_ghz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('cpu_threads', sa.Integer(), nullable=True),
    sa.Column('npu_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('npu_tops', sa.Float(), nullable=True),
    sa.Column('ai_ready', sa.Boolean(), nullable=False),
    sa.Column('ai_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gpu_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gpu_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gpu_cores', sa.Integer(), nullable=True),
    sa.Column('media_engine_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('ram_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ram_upgradable', sa.Boolean(), nullable=False),
    sa.Column('max_ram_gb', sa.Integer(), nullable=True),
    sa.Column('ssd_gb', sa.Integer(), nullable=False),
    sa.Column('storage_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('storage_upgradable', sa.Boolean(), nullable=False),
    sa.Column('expansion_slots_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_size_inch', sa.Float(), nullable=False),
    sa.Column('display_resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_refresh_rate_hz', sa.Integer(), nullable=True),
    sa.Column('display_brightness_nits', sa.Integer(), nullable=True),
    sa.Column('touchscreen', sa.Boolean(), nullable=False),
    sa.Column('external_display_support', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('dimensions_cm', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('battery_wh', sa.Float(), nullable=False),
    sa.Column('power_supply_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('os', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ports_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wifi_standard', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bluetooth_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('keyboard_touchpad_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('camera_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('facial_recognition', sa.Boolean(), nullable=False),
    sa.Column('fingerprint_reader', sa.Boolean(), nullable=False),
    sa.Column('security_features', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('materials_and_certifications', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('microsoft_office_included', sa.Boolean(), nullable=False),
    sa.Column('bundled_accessories', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('warranty_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['laptop_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laptops_model_code'), 'laptops', ['model_code'], unique=True)
    op.create_table('raw_scrap_laptops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('raw_product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_specs_dump', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['laptop_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_scrap_laptops_source_url'), 'raw_scrap_laptops', ['source_url'], unique=True)
    op.create_table('conversation_laptops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('laptop_id', sa.Uuid(), nullable=False),
    sa.Column('pick_score', sa.Integer(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_laptops_conversation_id'), 'conversation_laptops', ['conversation_id'], unique=False)
    op.create_table('laptop_customizations',
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('option_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_add_rm', sa.Float(), nullable=False),
    sa.Column('dependency_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('laptop_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laptop_customizations_laptop_id'), 'laptop_customizations', ['laptop_id'], unique=False)
    op.create_table('laptop_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('laptop_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('laptop_id')
    )
    op.create_table('laptop_price_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('laptop_id', sa.Uuid(), nullable=False),
    sa.Column('price_rm', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laptop_price_history_laptop_id'), 'laptop_price_history', ['laptop_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('pipeline_eval_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('gate_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('top_score', sa.Float(), nullable=True),
    sa.Column('relaxed_field', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('relaxed_from', sa.Float(), nullable=True),
    sa.Column('relaxed_to', sa.Float(), nullable=True),
    sa.Column('bottleneck', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('result_laptop_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_eval_logs_conversation_id'), 'pipeline_eval_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_pipeline_eval_logs_user_id'), 'pipeline_eval_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_eval_logs_user_id'), table_name='pipeline_eval_logs')
    op.drop_index(op.f('ix_pipeline_eval_logs_conversation_id'), table_name='pipeline_eval_logs')
    op.drop_table('pipeline_eval_logs')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_laptop_price_history_laptop_id'), table_name='laptop_price_history')
    op.drop_table('laptop_price_history')
    op.drop_table('laptop_embeddings')
    op.drop_index(op.f('ix_laptop_customizations_laptop_id'), table_name='laptop_customizations')
    op.drop_table('laptop_customizations')
    op.drop_index(op.f('ix_conversation_laptops_conversation_id'), table_name='conversation_laptops')
    op.drop_table('conversation_laptops')
    op.drop_index(op.f('ix_raw_scrap_laptops_source_url'), table_name='raw_scrap_laptops')
    op.drop_table('raw_scrap_laptops')
    op.drop_index(op.f('ix_laptops_model_code'), table_name='laptops')
    op.drop_table('laptops')
    op.drop_index(op.f('ix_laptop_user_preference_user_id'), table_name='laptop_user_preference')
    op.drop_table('laptop_user_preference')
    op.drop_index(op.f('ix_laptop_scrape_urls_url'), table_name='laptop_scrape_urls')
    op.drop_table('laptop_scrape_urls')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_laptop_brands_name'), table_name='laptop_brands')
    op.drop_table('laptop_brands')
    op.drop_index(op.f('ix_gpu_benchmarks_gpu_name'), table_name='gpu_benchmarks')
    op.drop_table('gpu_benchmarks')
    op.drop_index(op.f('ix_cpu_benchmarks_cpu_name'), table_name='cpu_benchmarks')
    op.drop_table('cpu_benchmarks')
    # ### end Alembic commands ###
