"""add evidence_tier_reviewed_at to youtube_channels

Revision ID: 6301c2f3b369
Revises: d1f21e5d2152
Create Date: 2026-08-24 17:46:16.766479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6301c2f3b369'
down_revision: Union[str, Sequence[str], None] = 'd1f21e5d2152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Nullable with NO server_default, deliberately. evidence_tier alone cannot
    distinguish "a human confirmed tier_2" from "nobody looked" — both are the
    same byte — and the aggregator now orders on that byte. A server default
    here would stamp every pre-existing row as reviewed and destroy exactly the
    distinction the column is being added to make. NULL must mean unreviewed.

    Timestamps for the reviewed rows are written by
    app/scripts/apply_channel_metadata.py, not here: which channels a human
    actually looked at is not something a migration can know.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_channels', sa.Column('evidence_tier_reviewed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_channels', 'evidence_tier_reviewed_at')
    # ### end Alembic commands ###
