"""add video_description to raw_youtube_reviews

Revision ID: 7c66592b531e
Revises: 2d645c884ece
Create Date: 2026-08-25 14:24:55.216129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c66592b531e'
down_revision: Union[str, Sequence[str], None] = '2d645c884ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Nullable with NO server_default, deliberately: NULL has to keep meaning
    # "never fetched" for the 88 rows that predate this column, so the backfill
    # (POST /reviews/backfill-descriptions) can find them. A server_default of
    # '' would stamp every one of them with "we looked and there was nothing" —
    # the same trap transcript_attempts' server_default '0' set, where 28 rows
    # holding full transcripts read as never attempted.
    op.add_column('raw_youtube_reviews', sa.Column('video_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_youtube_reviews', 'video_description')
    # ### end Alembic commands ###
