"""update latest laptop tbl

Revision ID: 82a7e9d6fc2b
Revises: 1ae7fc1d26e1
Create Date: 2026-06-14 01:36:09.463688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '82a7e9d6fc2b'
down_revision: Union[str, Sequence[str], None] = '1ae7fc1d26e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptops', sa.Column('processor_ghz', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('cpu_cores', sa.Integer(), nullable=True))
    op.add_column('laptops', sa.Column('cpu_threads', sa.Integer(), nullable=True))
    op.add_column('laptops', sa.Column('npu_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('npu_tops', sa.Float(), nullable=True))
    op.add_column('laptops', sa.Column('ai_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('laptops', sa.Column('gpu_cores', sa.Integer(), nullable=True))
    op.add_column('laptops', sa.Column('media_engine_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('ram_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('ram_upgradable', sa.Boolean(), nullable=False))
    op.add_column('laptops', sa.Column('max_ram_gb', sa.Integer(), nullable=True))
    op.add_column('laptops', sa.Column('storage_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('storage_upgradable', sa.Boolean(), nullable=False))
    op.add_column('laptops', sa.Column('expansion_slots_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('display_resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('display_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('display_brightness_nits', sa.Integer(), nullable=True))
    op.add_column('laptops', sa.Column('touchscreen', sa.Boolean(), nullable=False))
    op.add_column('laptops', sa.Column('external_display_support', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('dimensions_cm', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('power_supply_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('laptops', sa.Column('ports_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('laptops', sa.Column('wifi_standard', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('bluetooth_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('keyboard_touchpad_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('audio_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('camera_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('facial_recognition', sa.Boolean(), nullable=False))
    op.add_column('laptops', sa.Column('fingerprint_reader', sa.Boolean(), nullable=False))
    op.add_column('laptops', sa.Column('security_features', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('materials_and_certifications', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('microsoft_office_included', sa.Boolean(), nullable=False))
    op.add_column('laptops', sa.Column('bundled_accessories', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('warranty_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('laptops', 'battery_wh',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_column('laptops', 'microsoft_office')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptops', sa.Column('microsoft_office', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('laptops', 'battery_wh',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('laptops', 'warranty_details')
    op.drop_column('laptops', 'bundled_accessories')
    op.drop_column('laptops', 'microsoft_office_included')
    op.drop_column('laptops', 'materials_and_certifications')
    op.drop_column('laptops', 'security_features')
    op.drop_column('laptops', 'fingerprint_reader')
    op.drop_column('laptops', 'facial_recognition')
    op.drop_column('laptops', 'camera_details')
    op.drop_column('laptops', 'audio_details')
    op.drop_column('laptops', 'keyboard_touchpad_details')
    op.drop_column('laptops', 'bluetooth_version')
    op.drop_column('laptops', 'wifi_standard')
    op.drop_column('laptops', 'ports_summary')
    op.drop_column('laptops', 'colors')
    op.drop_column('laptops', 'power_supply_details')
    op.drop_column('laptops', 'dimensions_cm')
    op.drop_column('laptops', 'external_display_support')
    op.drop_column('laptops', 'touchscreen')
    op.drop_column('laptops', 'display_brightness_nits')
    op.drop_column('laptops', 'display_type')
    op.drop_column('laptops', 'display_resolution')
    op.drop_column('laptops', 'expansion_slots_summary')
    op.drop_column('laptops', 'storage_upgradable')
    op.drop_column('laptops', 'storage_type')
    op.drop_column('laptops', 'max_ram_gb')
    op.drop_column('laptops', 'ram_upgradable')
    op.drop_column('laptops', 'ram_type')
    op.drop_column('laptops', 'media_engine_details')
    op.drop_column('laptops', 'gpu_cores')
    op.drop_column('laptops', 'ai_features')
    op.drop_column('laptops', 'npu_tops')
    op.drop_column('laptops', 'npu_model')
    op.drop_column('laptops', 'cpu_threads')
    op.drop_column('laptops', 'cpu_cores')
    op.drop_column('laptops', 'processor_ghz')
    # ### end Alembic commands ###
