"""create laptop customizations tbl

Revision ID: 89a86e2d5749
Revises: 82a7e9d6fc2b
Create Date: 2026-06-15 15:30:21.677529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '89a86e2d5749'
down_revision: Union[str, Sequence[str], None] = '82a7e9d6fc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laptop_customizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('laptop_id', sa.Uuid(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('option_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_add_rm', sa.Float(), nullable=False),
    sa.Column('dependency_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laptop_customizations_laptop_id'), 'laptop_customizations', ['laptop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_laptop_customizations_laptop_id'), table_name='laptop_customizations')
    op.drop_table('laptop_customizations')
    # ### end Alembic commands ###
