"""add transcript failure_reason, language, attempts to raw_youtube_reviews

Revision ID: 8e429682f918
Revises: e2c76b019f4d
Create Date: 2026-08-22 18:15:06.244666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8e429682f918'
down_revision: Union[str, Sequence[str], None] = 'e2c76b019f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_youtube_reviews', sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('raw_youtube_reviews', sa.Column('transcript_language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('raw_youtube_reviews', sa.Column('transcript_attempts', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_raw_youtube_reviews_failure_reason'), 'raw_youtube_reviews', ['failure_reason'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_youtube_reviews_failure_reason'), table_name='raw_youtube_reviews')
    op.drop_column('raw_youtube_reviews', 'transcript_attempts')
    op.drop_column('raw_youtube_reviews', 'transcript_language')
    op.drop_column('raw_youtube_reviews', 'failure_reason')
    # ### end Alembic commands ###
