"""add laptop price history table

Revision ID: 97cd57f18e98
Revises: 95483e847e0e
Create Date: 2026-06-25 22:57:30.197821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '97cd57f18e98'
down_revision: Union[str, Sequence[str], None] = '95483e847e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laptop_price_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('laptop_id', sa.Uuid(), nullable=False),
    sa.Column('price_rm', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laptop_price_history_laptop_id'), 'laptop_price_history', ['laptop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_laptop_price_history_laptop_id'), table_name='laptop_price_history')
    op.drop_table('laptop_price_history')
    # ### end Alembic commands ###
