"""add is_verified to user

Revision ID: b822221532ba
Revises: 09e0b89d409b
Create Date: 2026-05-30 19:33:27.828215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel as sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b822221532ba'
down_revision: Union[str, Sequence[str], None] = '09e0b89d409b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptops', sa.Column('ssd_gb', sa.Integer(), nullable=False))
    op.add_column('laptops', sa.Column('display_size_inch', sa.Float(), nullable=False))
    op.add_column('laptops', sa.Column('display_refresh_rate_hz', sa.Integer(), nullable=True))
    op.add_column('laptops', sa.Column('release_year', sa.Integer(), nullable=True))
    op.add_column('laptops', sa.Column('ai_ready', sa.Boolean(), nullable=False))
    op.add_column('laptops', sa.Column('microsoft_office', sa.Boolean(), nullable=False))
    op.add_column('laptops', sa.Column('os', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('gpu_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('laptops', sa.Column('processor_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'password')
    op.drop_column('laptops', 'processor_brand')
    op.drop_column('laptops', 'gpu_brand')
    op.drop_column('laptops', 'os')
    op.drop_column('laptops', 'microsoft_office')
    op.drop_column('laptops', 'ai_ready')
    op.drop_column('laptops', 'release_year')
    op.drop_column('laptops', 'display_refresh_rate_hz')
    op.drop_column('laptops', 'display_size_inch')
    op.drop_column('laptops', 'ssd_gb')
    # ### end Alembic commands ###
