"""split trust_tier into evidence_tier market_relevance review_language

Revision ID: d1f21e5d2152
Revises: 8e429682f918
Create Date: 2026-08-24 16:52:50.810733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1f21e5d2152'
down_revision: Union[str, Sequence[str], None] = '8e429682f918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_channels', sa.Column('evidence_tier', sqlmodel.sql.sqltypes.AutoString(), server_default='tier_2', nullable=False))
    op.add_column('youtube_channels', sa.Column('market_relevance', sqlmodel.sql.sqltypes.AutoString(), server_default='global', nullable=False))
    op.add_column('youtube_channels', sa.Column('review_language', sqlmodel.sql.sqltypes.AutoString(), server_default='en', nullable=False))
    # ### end Alembic commands ###

    # Backfill evidence_tier from trust_tier. This is lossless and needs no
    # human input: the values already in trust_tier carry the evidence sense
    # (the three tier_1 rows are all hands-on benchmarking channels), so the
    # split loses nothing by copying them across.
    #
    # market_relevance and review_language cannot be derived from trust_tier —
    # that is the entire point of splitting it. They take their server
    # defaults here and are set by app/scripts/seed_channel_fields.py, which
    # seeds review_language from the script of already-ingested video titles
    # and leaves market_relevance for a human. Seeding lives in a script, not
    # in this migration: a migration must not depend on the shape of
    # raw_youtube_reviews, and the assignment should be reviewable before it
    # is applied.
    op.execute("UPDATE youtube_channels SET evidence_tier = trust_tier")


def downgrade() -> None:
    """Downgrade schema.

    Genuinely reversible: trust_tier was never altered or renamed, so dropping
    the three new columns restores the previous state exactly. That is why the
    cutover keeps trust_tier live rather than renaming it in place.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_channels', 'review_language')
    op.drop_column('youtube_channels', 'market_relevance')
    op.drop_column('youtube_channels', 'evidence_tier')
    # ### end Alembic commands ###
