"""change image_url to image_urls array

Revision ID: ddbc0e4de136
Revises: eee71a25ba33
Create Date: 2026-06-09 19:33:55.454646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddbc0e4de136'
down_revision: Union[str, Sequence[str], None] = 'eee71a25ba33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_scrap_laptops', sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('raw_scrap_laptops', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_scrap_laptops', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('raw_scrap_laptops', 'image_urls')
    # ### end Alembic commands ###
