"""change laptop image url data type

Revision ID: e67b02a435fd
Revises: f3fcaa26fbe0
Create Date: 2026-06-10 20:51:49.322789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e67b02a435fd'
down_revision: Union[str, Sequence[str], None] = 'f3fcaa26fbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptops', sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('laptops', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptops', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('laptops', 'image_urls')
    # ### end Alembic commands ###
