"""add new column icons_url

Revision ID: f3fcaa26fbe0
Revises: e482248b8968
Create Date: 2026-06-10 17:28:16.879566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f3fcaa26fbe0'
down_revision: Union[str, Sequence[str], None] = 'e482248b8968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- STEP 1: FIX LAPTOP_BRANDS (icons_url) ---
    op.add_column('laptop_brands', sa.Column('icons_url', sa.String(), nullable=True))
    op.execute("UPDATE laptop_brands SET icons_url = 'https://example.com/default-icon.png'")
    op.alter_column('laptop_brands', 'icons_url', nullable=False)
    op.drop_constraint(op.f('laptop_brands_name_key'), 'laptop_brands', type_='unique')
    
    # --- STEP 2: FIX LAPTOPS (brand_id) ---
    # Add brand_id allowing NULL values temporarily
    op.add_column('laptops', sa.Column('brand_id', sa.Uuid(), nullable=True))
    
    # Data Migration: Map the old 'brand' string to the new 'laptop_brands.id'
    op.execute("""
        UPDATE laptops 
        SET brand_id = laptop_brands.id
        FROM laptop_brands 
        WHERE laptops.brand = laptop_brands.name
    """)
    
    # Ensure no orphan laptop rows remain without a valid brand_id (assign a fallback if needed)
    # If all your laptops have matching names in laptop_brands, this step updates nothing.
    op.execute("""
        UPDATE laptops 
        SET brand_id = (SELECT id FROM laptop_brands LIMIT 1)
        WHERE brand_id IS NULL
    """)
    
    # Enforce NOT NULL constraint now that everything is mapped
    op.alter_column('laptops', 'brand_id', nullable=False)
    
    # Create the foreign key constraint
    op.create_foreign_key(None, 'laptops', 'laptop_brands', ['brand_id'], ['id'])
    
    # Drop the old 'brand' text column safely
    op.drop_column('laptops', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptops', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'laptops', type_='foreignkey')
    op.drop_column('laptops', 'brand_id')
    op.create_unique_constraint(op.f('laptop_brands_name_key'), 'laptop_brands', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('laptop_brands', 'icons_url')
    # ### end Alembic commands ###
