"""add youtube review ingestion tables

Revision ID: fe5716d7dbf4
Revises: 9962eb7ee808
Create Date: 2026-07-01 21:42:09.316759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe5716d7dbf4'
down_revision: Union[str, Sequence[str], None] = '9962eb7ee808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_img_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trust_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_channels_channel_id'), 'youtube_channels', ['channel_id'], unique=True)
    op.create_table('laptop_review_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('laptop_id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp_start_seconds', sa.Integer(), nullable=False),
    sa.Column('timestamp_end_seconds', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('sentiment_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laptop_review_chunks_laptop_id'), 'laptop_review_chunks', ['laptop_id'], unique=False)
    op.create_index(op.f('ix_laptop_review_chunks_video_id'), 'laptop_review_chunks', ['video_id'], unique=False)
    op.create_table('laptop_review_summary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('laptop_id', sa.Uuid(), nullable=False),
    sa.Column('aggregated_strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aggregated_weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laptop_review_summary_laptop_id'), 'laptop_review_summary', ['laptop_id'], unique=True)
    op.create_table('raw_youtube_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('raw_transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matched_laptop_id', sa.Uuid(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.channel_id'], ),
    sa.ForeignKeyConstraint(['matched_laptop_id'], ['laptops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_youtube_reviews_channel_id'), 'raw_youtube_reviews', ['channel_id'], unique=False)
    op.create_index(op.f('ix_raw_youtube_reviews_video_id'), 'raw_youtube_reviews', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_youtube_reviews_video_id'), table_name='raw_youtube_reviews')
    op.drop_index(op.f('ix_raw_youtube_reviews_channel_id'), table_name='raw_youtube_reviews')
    op.drop_table('raw_youtube_reviews')
    op.drop_index(op.f('ix_laptop_review_summary_laptop_id'), table_name='laptop_review_summary')
    op.drop_table('laptop_review_summary')
    op.drop_index(op.f('ix_laptop_review_chunks_video_id'), table_name='laptop_review_chunks')
    op.drop_index(op.f('ix_laptop_review_chunks_laptop_id'), table_name='laptop_review_chunks')
    op.drop_table('laptop_review_chunks')
    op.drop_index(op.f('ix_youtube_channels_channel_id'), table_name='youtube_channels')
    op.drop_table('youtube_channels')
    # ### end Alembic commands ###
