"""
Migrations, run against a throwaway database instead of production.

This is the item the tier was promoted for. a3f7d21c6b84 was applied straight to
Supabase because that is where DATABASE_URL points; it happened to be additive
and reversible. What follows is the check that the next one is too, run
somewhere it does not matter.
"""

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import text
from sqlmodel import SQLModel

from tests.integration.conftest import _production_urls

pytestmark = pytest.mark.integration


def _alembic_config(url: str) -> Config:
    cfg = Config("alembic.ini")
    cfg.set_main_option("sqlalchemy.url", url)
    return cfg


@pytest.fixture
def empty_db(engine):
    """A genuinely empty database — no tables, no alembic_version."""
    SQLModel.metadata.drop_all(engine)
    with engine.connect() as conn:
        conn.execute(text("DROP TABLE IF EXISTS alembic_version"))
        conn.commit()
    yield engine
    SQLModel.metadata.drop_all(engine)
    with engine.connect() as conn:
        conn.execute(text("DROP TABLE IF EXISTS alembic_version"))
        conn.commit()


def test_the_tier_is_not_pointed_at_production(database_url):
    """
    The guard, asserted rather than assumed. Everything in this file drops
    tables; the production database is one environment variable away, and that
    proximity is exactly what put a3f7d21c6b84 on Supabase.
    """
    assert "supabase" not in database_url
    for production in _production_urls():
        assert database_url != production


def test_upgrade_head_from_empty(empty_db, database_url):
    """Catches a migration that only works on a database which already has the
    table it edits — the state every local database is in and a fresh deploy
    is not."""
    command.upgrade(_alembic_config(database_url), "head")
    with empty_db.connect() as conn:
        version = conn.execute(text("SELECT version_num FROM alembic_version")).scalar()
    assert version


def test_exactly_one_head():
    """Two heads means two people branched the history and nobody merged. The
    second one silently never runs."""
    script = ScriptDirectory.from_config(Config("alembic.ini"))
    heads = script.get_heads()
    assert len(heads) == 1, f"expected one head, found {heads}"


def test_alembic_check_is_clean(empty_db, database_url):
    """
    Model/schema drift. A model declared differently from the live column is how
    a JSONB column gets silently downgraded to JSON by an autogenerated ALTER,
    and a table whose module alembic/env.py never imports is absent from the
    metadata entirely — which autogenerate reads as "drop it".
    """
    cfg = _alembic_config(database_url)
    command.upgrade(cfg, "head")
    command.check(cfg)  # raises AutogenerateDiffsDetected if anything differs


def test_every_migration_downgrades_and_re_upgrades(empty_db, database_url):
    """
    THE CHECK THAT WOULD HAVE MADE THE a3f7d21c6b84 DECISION REVERSIBLE.

    Walks the whole history down to base and back up. A downgrade that was never
    run is not a rollback plan — it is a function nobody has executed, and the
    moment it is needed is the worst moment to find out it raises.
    """
    cfg = _alembic_config(database_url)
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")

    with empty_db.connect() as conn:
        remaining = conn.execute(
            text(
                "SELECT count(*) FROM information_schema.tables "
                "WHERE table_schema = 'public' AND table_name <> 'alembic_version'"
            )
        ).scalar()
    assert remaining == 0, f"{remaining} tables survived a full downgrade"

    command.upgrade(cfg, "head")


def test_retrieval_fallback_column_exists_after_upgrade(empty_db, database_url):
    """
    The specific column from a3f7d21c6b84, checked the way the migration should
    have been before it ran on production: NOT NULL with a server default, so
    the existing rows on a populated table stay valid.
    """
    command.upgrade(_alembic_config(database_url), "head")
    with empty_db.connect() as conn:
        row = conn.execute(
            text(
                "SELECT is_nullable, column_default FROM information_schema.columns "
                "WHERE table_name = 'pipeline_eval_logs' "
                "AND column_name = 'retrieval_fallback'"
            )
        ).first()
    assert row is not None, "the column is missing after upgrade head"
    is_nullable, default = row
    assert is_nullable == "NO"
    assert default is not None and "false" in default.lower()
