"""
Migrations, run against a throwaway database instead of production.

This is the item the tier was promoted for. a3f7d21c6b84 was applied straight to
Supabase because that is where DATABASE_URL points; it happened to be additive
and reversible. What follows is the check that the next one is too, run
somewhere it does not matter.
"""

import os
import pathlib
import re

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import text
from sqlmodel import SQLModel

from tests.integration.conftest import (
    assert_not_production,
    drop_everything,
    project_ref,
)

pytestmark = pytest.mark.integration


def _alembic_config(url: str) -> Config:
    cfg = Config("alembic.ini")
    cfg.set_main_option("sqlalchemy.url", url)
    # Suppress alembic/env.py's fileConfig() call. logging.config.fileConfig
    # defaults to disable_existing_loggers=True, so running a migration
    # IN-PROCESS silently switches off every logger already created -- which
    # made three unrelated unit tests fail, but only when this file ran first.
    # Production is unaffected: the deploy runs alembic as its own process.
    cfg.config_file_name = None
    return cfg


@pytest.fixture
def empty_db(engine):
    """A genuinely empty database — no tables, no alembic_version.

    drop_everything, not SQLModel.metadata.drop_all: these tests leave the
    database holding the MIGRATION-created schema, which includes tables this
    tier never imports as models. Dropping only the known ones fails on the
    foreign keys the rest still hold.
    """
    drop_everything(engine)
    with engine.connect() as conn:
        conn.execute(text("DROP TABLE IF EXISTS alembic_version"))
        conn.commit()
    yield engine
    # Put the database back the way the session-scoped `clean_schema` fixture
    # left it. That fixture builds the model schema ONCE for the whole session;
    # these tests migrate and drop underneath it, so without this restore every
    # later integration file finds no tables -- which showed up as 8 errors in
    # the full run and nothing at all when this file ran alone.
    drop_everything(engine)
    with engine.connect() as conn:
        conn.execute(text("DROP TABLE IF EXISTS alembic_version"))
        conn.commit()
    SQLModel.metadata.create_all(engine)


def test_the_tier_is_not_pointed_at_production(database_url):
    """
    The guard, asserted rather than assumed. Everything in this file drops
    tables; production is one project ref away, and that proximity is exactly
    what put a3f7d21c6b84 on Supabase.
    """
    assert_not_production(database_url)
    assert project_ref(database_url) != os.environ.get("PRODUCTION_DB_REF")


def test_upgrade_head_from_empty(empty_db, database_url):
    """Catches a migration that only works on a database which already has the
    table it edits — the state every local database is in and a fresh deploy
    is not."""
    command.upgrade(_alembic_config(database_url), "head")
    with empty_db.connect() as conn:
        version = conn.execute(text("SELECT version_num FROM alembic_version")).scalar()
    assert version


def test_exactly_one_head():
    """Two heads means two people branched the history and nobody merged. The
    second one silently never runs."""
    script = ScriptDirectory.from_config(Config("alembic.ini"))
    heads = script.get_heads()
    assert len(heads) == 1, f"expected one head, found {heads}"


def test_alembic_check_is_clean(empty_db, database_url):
    """
    Model/schema drift. A model declared differently from the live column is how
    a JSONB column gets silently downgraded to JSON by an autogenerated ALTER,
    and a table whose module alembic/env.py never imports is absent from the
    metadata entirely — which autogenerate reads as "drop it".
    """
    cfg = _alembic_config(database_url)
    command.upgrade(cfg, "head")
    command.check(cfg)  # raises AutogenerateDiffsDetected if anything differs


def test_the_whole_history_downgrades_to_base(empty_db, database_url):
    """
    Half of the reversibility check, and the half that passes.

    Every one of the 22 revisions downgrades without raising, and the schema is
    empty afterwards. Run for the first time 2026-09-14 — before that these were
    functions nobody had executed, and the moment a rollback is needed is the
    worst moment to discover one raises.
    """
    cfg = _alembic_config(database_url)
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")

    with empty_db.connect() as conn:
        remaining = conn.execute(
            text(
                "SELECT count(*) FROM information_schema.tables "
                "WHERE table_schema = 'public' AND table_name <> 'alembic_version'"
            )
        ).scalar()
    assert remaining == 0, f"{remaining} tables survived a full downgrade"


@pytest.mark.xfail(
    strict=True,
    reason=(
        "REAL BUG, reported not fixed. Downgrading to base drops every TABLE but "
        "leaves the enum TYPE 'messagerole' behind: 453fffc97e7b (init_all_tables) "
        "creates it implicitly via sa.Enum on messages.role, and its autogenerated "
        "downgrade only calls op.drop_table -- SQLAlchemy emits CREATE TYPE on "
        "table create but never DROP TYPE on drop. Re-upgrading then dies on "
        "'type messagerole already exists'."
    ),
)
def test_the_history_round_trips(empty_db, database_url):
    """
    The other half: down to base, then back up again.

    A rollback nobody can undo is not a rollback, it is a one-way door with a
    reassuring name on it.
    """
    cfg = _alembic_config(database_url)
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")


@pytest.fixture
def no_vector_extension(empty_db):
    """
    Take the tier's own safety net away.

    The `engine` fixture runs CREATE EXTENSION before anything else, which is
    exactly what hid this bug: the defence (something creates the extension) and
    the detector (a test that the migration creates it) were the same statement,
    so the test could not fail. This fixture separates them — it removes the
    extension that the fixture installed, so what follows measures the
    migrations alone.

    Safe because `empty_db` has already dropped every table, so nothing depends
    on the type.
    """
    with empty_db.connect() as conn:
        conn.execute(text("DROP EXTENSION IF EXISTS vector CASCADE"))
        conn.commit()
    yield empty_db
    with empty_db.connect() as conn:
        conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))
        conn.commit()


def test_upgrade_from_empty_creates_its_own_pgvector(no_vector_extension, database_url):
    """
    THE FROM-EMPTY TEST. 453fffc97e7b creates a VECTOR(768) column, so something
    has to create the extension first, and until now nothing in the migration
    history did — `alembic upgrade head` on a genuinely fresh database failed
    with 'type "vector" does not exist'.

    That mattered beyond tidiness: the Dockerfile runs `alembic upgrade head`
    BEFORE uvicorn, so the deploy has never once succeeded from empty. It works
    in production only because the extension was already there. Disaster
    recovery, a region move, or a new staging project would each have hit it.
    """
    with no_vector_extension.connect() as conn:
        assert not conn.execute(
            text("SELECT count(*) FROM pg_extension WHERE extname = 'vector'")
        ).scalar(), "the extension is still installed; this test proves nothing"

    command.upgrade(_alembic_config(database_url), "head")

    with no_vector_extension.connect() as conn:
        installed = conn.execute(
            text("SELECT extversion FROM pg_extension WHERE extname = 'vector'")
        ).scalar()
        embedding_type = conn.execute(
            text(
                "SELECT udt_name FROM information_schema.columns "
                "WHERE table_name = 'laptop_embeddings' AND column_name = 'embedding'"
            )
        ).scalar()
    assert installed, "the migrations did not create the extension"
    assert embedding_type == "vector"


def test_a_migration_owns_the_extension(database_url):
    """The prerequisite is expressed in the migration history, not left to
    application startup that runs after it."""
    # Matches the executable statement, not the words. An earlier version of
    # this test searched the file text and passed on the docstring that
    # explains the statement, which is a test that cannot fail.
    creators = [
        m.name
        for m in pathlib.Path("alembic/versions").glob("*.py")
        if re.search(r"op\.execute\(\s*[\"']CREATE EXTENSION", m.read_text(encoding="utf-8"))
    ]
    assert creators, "no migration executes CREATE EXTENSION for pgvector"


def test_retrieval_fallback_column_exists_after_upgrade(empty_db, database_url):
    """
    The specific column from a3f7d21c6b84, checked the way the migration should
    have been before it ran on production: NOT NULL with a server default, so
    the existing rows on a populated table stay valid.
    """
    command.upgrade(_alembic_config(database_url), "head")
    with empty_db.connect() as conn:
        row = conn.execute(
            text(
                "SELECT is_nullable, column_default FROM information_schema.columns "
                "WHERE table_name = 'pipeline_eval_logs' "
                "AND column_name = 'retrieval_fallback'"
            )
        ).first()
    assert row is not None, "the column is missing after upgrade head"
    is_nullable, default = row
    assert is_nullable == "NO"
    assert default is not None and "false" in default.lower()
